2014-06-26 16:58:10,089 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:10,089 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:10,237 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:10,252 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:10,292 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:10,293 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:10,344 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:10,363 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:10,398 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:37,633 Exception on /debug [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: debug
2014-06-26 16:58:57,351 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:57,786 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:57,802 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:57,803 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:58,027 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:58,028 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:58,068 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:58,094 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 16:58:58,113 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-26 20:29:02 [5318] [CRITICAL] WORKER TIMEOUT (pid:5323)
2014-06-26 20:29:02 [5318] [CRITICAL] WORKER TIMEOUT (pid:5327)
2014-06-26 20:29:02 [5318] [CRITICAL] WORKER TIMEOUT (pid:5334)
2014-06-26 20:29:02 [5318] [CRITICAL] WORKER TIMEOUT (pid:5337)
2014-06-26 20:29:02 [5318] [CRITICAL] WORKER TIMEOUT (pid:5338)
2014-06-26 20:29:02 [5318] [CRITICAL] WORKER TIMEOUT (pid:5339)
2014-06-27 10:05:21,346 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 10:05:21,411 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 10:05:21,444 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 10:05:21,550 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 10:05:21,582 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 10:05:21,625 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 10:05:21,627 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 10:05:21,736 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 10:05:21,736 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:49:27,478 Exception on /instructions/instruct-ready.html [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: instructions/instruct-ready.html
2014-06-27 11:49:58,906 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:49:58,906 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:49:58,910 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:49:58,910 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:49:58,906 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:49:58,910 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:49:58,910 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:49:58,915 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:49:58,915 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 11:50:21,040 Exception on /instructions/instruct-ready.html [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: instructions/instruct-ready.html
2014-06-27 12:44:21 [11871] [CRITICAL] WORKER TIMEOUT (pid:11877)
2014-06-27 12:44:21 [11871] [CRITICAL] WORKER TIMEOUT (pid:11878)
2014-06-27 12:44:21 [11871] [CRITICAL] WORKER TIMEOUT (pid:11880)
2014-06-27 12:44:21 [11871] [CRITICAL] WORKER TIMEOUT (pid:11883)
2014-06-27 12:44:30,231 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 12:44:30,231 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 12:44:30,232 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 12:44:30,233 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 13:01:53,652 Exception on /instructions/pretrial [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: instructions/pretrial
2014-06-27 13:02:46,537 Exception on /instructions/pretrial [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: instructions/pretrial
2014-06-27 13:03:22,487 Exception on /instructions/pretrial [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: instructions/pretrial
2014-06-27 16:50:40,540 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 16:50:40,540 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 16:50:40,542 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 16:50:40,543 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 16:50:40,544 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 16:50:40,546 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 16:50:40,547 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 16:50:40,548 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 16:50:40,549 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 21:27:35 [26053] [CRITICAL] WORKER TIMEOUT (pid:26065)
2014-06-27 21:27:35,889 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 22:26:35 [26053] [CRITICAL] WORKER TIMEOUT (pid:26058)
2014-06-27 22:26:35 [26053] [CRITICAL] WORKER TIMEOUT (pid:26060)
2014-06-27 22:26:35 [26053] [CRITICAL] WORKER TIMEOUT (pid:26061)
2014-06-27 22:26:35 [26053] [CRITICAL] WORKER TIMEOUT (pid:26062)
2014-06-27 22:26:35 [26053] [CRITICAL] WORKER TIMEOUT (pid:26063)
2014-06-27 22:26:35 [26053] [CRITICAL] WORKER TIMEOUT (pid:26064)
2014-06-27 22:26:35 [26053] [CRITICAL] WORKER TIMEOUT (pid:26066)
2014-06-27 22:26:35 [26053] [CRITICAL] WORKER TIMEOUT (pid:28793)
2014-06-27 22:26:36,746 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 22:26:36,919 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 22:26:36,952 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 22:26:37,054 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 22:26:37,059 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 22:26:37,082 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 22:26:37,101 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-27 22:26:37,130 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:07:34,214 Exception on /consent [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/user_utils.py", line 11, in new_func
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 285, in give_consent
    return render_template('consent.html', hitid = hitId, assignmentid=assignmentId, workerid=workerId)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: consent.html
2014-06-28 00:08:06,658 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:08:06,662 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:08:06,662 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:08:06,664 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:08:06,661 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:08:06,665 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:08:06,668 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:08:06,669 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:08:06,699 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:08:49,836 Exception on /instructions/ldtInstructions.html [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: instructions/ldtInstructions.html
2014-06-28 00:08:49,852 Exception on /instructions/ldtPretrial.html [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: instructions/ldtPretrial.html
2014-06-28 00:11:42,209 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:11:42,435 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:11:42,500 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:11:42,616 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:11:42,710 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:11:42,778 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:11:42,873 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:11:42,910 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 00:11:42,935 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 10:21:56 [5744] [CRITICAL] WORKER TIMEOUT (pid:5760)
2014-06-28 10:21:56 [5744] [CRITICAL] WORKER TIMEOUT (pid:5763)
2014-06-28 10:21:56 [5744] [CRITICAL] WORKER TIMEOUT (pid:5766)
2014-06-28 10:21:56 [5744] [CRITICAL] WORKER TIMEOUT (pid:5767)
2014-06-28 10:21:56 [5744] [CRITICAL] WORKER TIMEOUT (pid:5750)
2014-06-28 10:21:56 [5744] [CRITICAL] WORKER TIMEOUT (pid:5756)
2014-06-28 10:21:57,916 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 10:21:57,916 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 10:21:57,917 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 10:21:57,921 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 10:21:57,921 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 10:21:57,924 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 12:07:52 [5744] [CRITICAL] WORKER TIMEOUT (pid:7869)
2014-06-28 12:07:52 [5744] [CRITICAL] WORKER TIMEOUT (pid:5753)
2014-06-28 12:07:52 [5744] [CRITICAL] WORKER TIMEOUT (pid:7866)
2014-06-28 12:07:52 [5744] [CRITICAL] WORKER TIMEOUT (pid:7867)
2014-06-28 12:07:52 [5744] [CRITICAL] WORKER TIMEOUT (pid:7868)
2014-06-28 12:07:52 [5744] [CRITICAL] WORKER TIMEOUT (pid:7870)
2014-06-28 12:07:52 [5744] [CRITICAL] WORKER TIMEOUT (pid:7871)
2014-06-28 12:07:53,015 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 12:07:53,075 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 12:07:53,102 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 12:07:53,143 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 12:07:53,153 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 12:07:53,162 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 12:07:53,227 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-28 23:21:53 [5744] [CRITICAL] WORKER TIMEOUT (pid:9632)
2014-06-28 23:22:00,161 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 15:36:04 [5744] [CRITICAL] WORKER TIMEOUT (pid:9633)
2014-06-29 15:36:04 [5744] [CRITICAL] WORKER TIMEOUT (pid:9636)
2014-06-29 15:36:04 [5744] [CRITICAL] WORKER TIMEOUT (pid:5749)
2014-06-29 15:36:04 [5744] [CRITICAL] WORKER TIMEOUT (pid:9629)
2014-06-29 15:36:04 [5744] [CRITICAL] WORKER TIMEOUT (pid:14651)
2014-06-29 15:36:04 [5744] [CRITICAL] WORKER TIMEOUT (pid:9630)
2014-06-29 15:36:07,845 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 15:36:07,846 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 15:36:07,850 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 15:36:07,853 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 15:36:07,856 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 15:36:07,862 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:29:58 [5744] [CRITICAL] WORKER TIMEOUT (pid:18062)
2014-06-29 19:29:59 [5744] [CRITICAL] WORKER TIMEOUT (pid:9631)
2014-06-29 19:29:59 [5744] [CRITICAL] WORKER TIMEOUT (pid:9634)
2014-06-29 19:29:59 [5744] [CRITICAL] WORKER TIMEOUT (pid:5757)
2014-06-29 19:30:07,711 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:30:07,712 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:30:07,712 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:30:07,714 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:02,416 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:02,420 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:02,463 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:03,968 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:03,979 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:04,091 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:04,120 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:04,121 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:04,141 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:04,170 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:04,170 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-29 19:36:04,185 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 11:06:41,087 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 11:06:41,087 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 11:06:41,120 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 11:06:41,120 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 11:06:41,162 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 11:06:41,185 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 11:06:41,196 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 11:06:41,236 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 11:06:41,241 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 13:54:43,189 Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: login
2014-06-30 13:54:47,943 Exception on /admin [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: admin
2014-06-30 13:54:50,942 Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: dashboard
2014-06-30 13:57:24,602 Exception on /templates/list.html [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: templates/list.html
2014-06-30 14:44:16,264 Exception on /calibrate [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: calibrate
2014-06-30 14:45:35 [11174] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
2014-06-30 14:45:35 [11175] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
2014-06-30 14:45:35 [11176] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
2014-06-30 14:45:35 [11173] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
2014-06-30 14:45:35 [11177] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
2014-06-30 14:45:35 [11185] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
2014-06-30 14:45:35 [11178] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
2014-06-30 14:45:35 [11188] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
2014-06-30 14:45:35 [11192] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment_server.py", line 44, in load
    return util.import_app("psiturk.experiment:start_app(%s)" % self.sandbox)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 64, in <module>
    from custom import custom_code
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 38
    return('{"yes":"no"}')
                         ^
IndentationError: unindent does not match any outer indentation level
2014-06-30 14:47:08,124 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:47:08,134 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:47:08,543 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:47:08,550 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:47:08,636 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:47:08,664 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:47:08,674 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:47:08,734 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:47:08,741 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:48:29,191 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:48:29,386 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:48:29,430 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:48:29,679 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:48:29,713 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:48:29,735 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:48:29,757 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:48:29,788 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:48:29,864 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:51:09,698 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:51:09,764 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:51:09,794 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:51:09,817 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:51:09,832 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:51:09,867 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:51:09,883 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:51:09,924 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 14:51:09,948 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:01:26,836 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:01:27,021 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:01:27,137 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:01:27,269 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:01:27,349 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:01:27,413 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:01:27,480 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:01:27,499 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:01:27,500 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:18:54,507 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:18:54,534 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:18:54,569 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:18:54,661 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:18:54,742 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:18:54,837 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:18:54,865 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:18:54,869 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:18:54,947 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:19:01,881 Exception on /calibrate [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: calibrate
2014-06-30 15:27:24,140 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:27:24,240 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:27:24,495 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:27:24,595 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:27:24,715 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:27:24,809 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:27:24,855 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:27:24,905 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:27:24,943 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:28:38,927 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 39, in checkCaptcha
    response = requests.post("http://httpbin.org/post", data=payload)
NameError: global name 'requests' is not defined
2014-06-30 15:46:11,260 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 39, in checkCaptcha
    'remoteip': request.remote_addr,
NameError: global name 'requests' is not defined
2014-06-30 15:47:21,849 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:47:21,858 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:47:22,290 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:47:22,587 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:47:22,593 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:47:22,595 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:47:22,599 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:47:22,601 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:47:22,605 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:54:13,179 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:54:13,191 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:54:13,304 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:54:13,375 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:54:13,386 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:54:13,415 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:54:13,464 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:54:13,474 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:54:13,495 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:55:10,906 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:55:11,058 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:55:11,390 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:55:11,456 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:55:11,482 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:55:11,513 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:55:11,606 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:55:11,634 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:55:11,691 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:58:52,393 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:58:52,418 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:58:52,442 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:58:52,607 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:58:52,658 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:58:52,683 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:58:52,695 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:58:52,696 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 15:58:52,725 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:08:29,907 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:08:30,034 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:08:30,359 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:08:30,385 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:08:30,434 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:08:30,493 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:08:30,505 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:08:30,534 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:08:30,537 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:27,245 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:27,412 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:27,577 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:27,579 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:27,649 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:27,682 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:27,710 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:27,794 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:27,805 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:09:53,132 Exception on /checkCaptcha [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: checkCaptcha
2014-06-30 16:12:46,723 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:12:46,846 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:12:46,909 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:12:46,932 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:12:46,965 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:12:47,017 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:12:47,036 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:12:47,050 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:12:47,097 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:16:10,101 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:16:10,311 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:16:10,520 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:16:10,540 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:16:10,556 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:16:10,740 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:16:10,757 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:16:10,788 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:16:10,796 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:13,603 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:13,717 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:13,718 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:13,756 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:13,934 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:13,971 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:13,999 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:14,003 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:14,069 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:20:34,510 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 48, in checkCaptcha
    response = requests.post("http://www.google.com/recaptcha/api/verify", data=payload)
NameError: global name 'requests' is not defined
2014-06-30 16:20:41,783 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 48, in checkCaptcha
    response = requests.post("http://www.google.com/recaptcha/api/verify", data=payload)
NameError: global name 'requests' is not defined
2014-06-30 16:20:42,341 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 48, in checkCaptcha
    response = requests.post("http://www.google.com/recaptcha/api/verify", data=payload)
NameError: global name 'requests' is not defined
2014-06-30 16:21:48,351 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:21:48,475 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:21:48,789 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:21:48,920 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:21:49,000 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:21:49,016 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:21:49,032 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:21:49,047 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:21:49,116 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:21:55,377 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = requests.post("http://www.google.com/recaptcha/api/verify", data=payload)
NameError: global name 'requests' is not defined
2014-06-30 16:21:56,826 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = requests.post("http://www.google.com/recaptcha/api/verify", data=payload)
NameError: global name 'requests' is not defined
2014-06-30 16:22:36,601 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:22:36,764 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:22:36,970 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:22:37,196 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:22:37,239 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:22:37,309 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:22:37,320 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:22:37,327 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:22:37,353 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:22:44,070 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = request.post("http://www.google.com/recaptcha/api/verify", data=payload)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'post'
2014-06-30 16:22:44,704 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = request.post("http://www.google.com/recaptcha/api/verify", data=payload)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'post'
2014-06-30 16:22:45,055 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = request.post("http://www.google.com/recaptcha/api/verify", data=payload)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'post'
2014-06-30 16:22:45,202 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = request.post("http://www.google.com/recaptcha/api/verify", data=payload)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'post'
2014-06-30 16:22:45,410 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = request.post("http://www.google.com/recaptcha/api/verify", data=payload)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'post'
2014-06-30 16:23:01,632 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:01,855 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:02,117 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:02,226 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:02,299 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:02,388 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:02,392 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:02,405 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:02,456 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:13,211 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = request.post("http://www.google.com/recaptcha/api/verify", data=payload)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'post'
2014-06-30 16:23:51,571 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:51,642 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:51,827 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:51,840 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:51,958 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:52,003 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:52,034 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:52,046 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:52,077 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:23:55,562 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = request.post("http://www.google.com/recaptcha/api/verify", data=payload)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'post'
2014-06-30 16:23:56,069 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = request.post("http://www.google.com/recaptcha/api/verify", data=payload)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'post'
2014-06-30 16:24:16,241 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:24:16,261 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:24:16,338 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:24:16,424 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:24:16,432 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:24:16,452 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:24:16,459 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:24:16,558 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:24:16,589 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:24:19,030 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 49, in checkCaptcha
    response = request.post("http://www.google.com/recaptcha/api/verify", data=payload)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'post'
2014-06-30 16:25:52,469 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:25:52,720 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:25:52,733 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:25:52,754 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:25:53,001 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:25:53,026 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:25:53,057 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:25:53,128 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:25:53,165 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:26:05,839 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:26:09,267 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:26:12,765 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:26:15,059 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:26:15,530 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:26:15,842 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:26:16,025 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:27:56,621 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:27:57,420 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:27:57,459 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:28:11,093 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:28:11,245 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:28:11,280 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:28:11,335 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:28:11,448 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:28:11,522 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:28:11,560 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:28:11,583 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:28:11,622 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:28:13,961 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:28:14,506 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:28:14,688 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:28:14,817 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:29:18,104 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'Response' object is not callable
2014-06-30 16:29:50,754 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:29:51,049 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:29:51,092 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:29:51,143 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:29:51,307 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:29:51,313 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:29:51,427 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:29:51,445 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:29:51,452 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:32:24,447 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:32:24,579 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:32:24,742 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:32:24,778 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:32:24,887 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:32:24,979 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:32:24,987 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:32:25,015 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:32:25,034 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:09,113 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:09,317 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:09,660 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:09,663 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:09,805 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:09,807 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:09,820 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:09,839 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:09,880 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:28,494 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:28,528 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:28,689 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:28,754 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:28,825 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:28,889 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:28,895 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:28,920 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:36:28,945 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:38:23,880 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:38:23,888 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:38:23,913 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:38:23,969 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:38:24,122 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:38:24,139 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:38:24,141 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:38:24,155 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:38:24,225 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:40:53,196 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:40:53,341 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:40:53,650 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:40:53,726 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:40:53,857 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:40:53,917 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:40:53,933 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:40:53,960 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:40:53,990 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:55:45,472 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:55:45,561 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:55:45,692 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:55:45,781 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:55:45,825 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:55:45,876 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:55:45,918 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:55:45,950 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 16:55:46,000 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:43:31 [22157] [CRITICAL] WORKER TIMEOUT (pid:22178)
2014-06-30 19:43:31 [22157] [CRITICAL] WORKER TIMEOUT (pid:22162)
2014-06-30 19:43:31 [22157] [CRITICAL] WORKER TIMEOUT (pid:22163)
2014-06-30 19:43:31 [22157] [CRITICAL] WORKER TIMEOUT (pid:22164)
2014-06-30 19:43:31 [22157] [CRITICAL] WORKER TIMEOUT (pid:22169)
2014-06-30 19:43:31 [22157] [CRITICAL] WORKER TIMEOUT (pid:22170)
2014-06-30 19:43:31 [22157] [CRITICAL] WORKER TIMEOUT (pid:22171)
2014-06-30 19:43:31 [22157] [CRITICAL] WORKER TIMEOUT (pid:22174)
2014-06-30 19:43:37,596 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:43:37,598 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:43:37,600 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:43:37,603 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:43:37,603 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:43:37,606 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:43:37,611 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:43:37,612 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:44:28,222 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:44:28,288 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:44:28,350 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:44:28,375 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:44:28,390 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:44:28,410 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:44:28,424 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:44:28,438 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 19:44:28,439 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 20:26:05,732 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 20:26:05,763 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 20:26:05,862 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 20:26:05,900 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 20:26:05,917 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 20:26:05,920 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 20:26:05,952 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 20:26:05,978 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 20:26:05,978 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 23:22:30,385 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 23:22:30,406 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 23:22:30,406 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 23:22:30,711 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 23:22:30,723 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 23:22:30,976 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 23:22:31,051 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 23:22:31,073 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-06-30 23:22:31,214 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 08:45:42 [3960] [CRITICAL] WORKER TIMEOUT (pid:3968)
2014-07-01 08:45:42 [3960] [CRITICAL] WORKER TIMEOUT (pid:3969)
2014-07-01 08:45:42 [3960] [CRITICAL] WORKER TIMEOUT (pid:3970)
2014-07-01 08:45:42 [3960] [CRITICAL] WORKER TIMEOUT (pid:3971)
2014-07-01 08:45:42 [3960] [CRITICAL] WORKER TIMEOUT (pid:3972)
2014-07-01 08:45:42 [3960] [CRITICAL] WORKER TIMEOUT (pid:3974)
2014-07-01 08:45:42 [3960] [CRITICAL] WORKER TIMEOUT (pid:3965)
2014-07-01 08:45:42 [3960] [CRITICAL] WORKER TIMEOUT (pid:3966)
2014-07-01 08:45:42 [3960] [CRITICAL] WORKER TIMEOUT (pid:3967)
2014-07-01 08:45:43,708 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 08:45:43,809 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 08:45:43,898 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 08:45:44,179 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 08:45:44,224 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 08:45:44,335 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 08:45:44,357 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 08:45:44,402 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 08:45:44,448 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:05:17 [3960] [CRITICAL] WORKER TIMEOUT (pid:7072)
2014-07-01 10:05:25,870 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:17:15,588 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:17:15,592 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:17:15,652 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:17:15,657 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:17:15,678 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:17:15,680 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:17:15,680 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:17:15,701 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:17:15,709 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:48:06,829 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:48:06,831 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:48:06,904 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:48:06,976 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:48:07,128 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:48:07,132 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:48:07,142 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:48:07,206 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 10:48:07,219 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 11:11:00 [2983] [CRITICAL] WORKER TIMEOUT (pid:3026)
2014-07-01 11:11:00 [2983] [CRITICAL] WORKER TIMEOUT (pid:3009)
2014-07-01 11:11:00 [2983] [CRITICAL] WORKER TIMEOUT (pid:3011)
2014-07-01 11:11:00 [2983] [CRITICAL] WORKER TIMEOUT (pid:3017)
2014-07-01 11:11:00 [2983] [CRITICAL] WORKER TIMEOUT (pid:3018)
2014-07-01 11:11:00 [2983] [CRITICAL] WORKER TIMEOUT (pid:2988)
2014-07-01 11:11:00 [2983] [CRITICAL] WORKER TIMEOUT (pid:3021)
2014-07-01 11:11:00 [2983] [CRITICAL] WORKER TIMEOUT (pid:2990)
2014-07-01 11:11:00 [2983] [CRITICAL] WORKER TIMEOUT (pid:2994)
2014-07-01 11:11:01,082 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 11:11:01,159 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 11:11:01,181 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 11:11:01,252 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 11:11:01,290 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 11:11:01,335 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 11:11:01,351 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 11:11:01,353 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 11:11:01,372 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 13:05:42 [2983] [CRITICAL] WORKER TIMEOUT (pid:3752)
2014-07-01 13:05:42 [2983] [CRITICAL] WORKER TIMEOUT (pid:3754)
2014-07-01 13:05:42 [2983] [CRITICAL] WORKER TIMEOUT (pid:3758)
2014-07-01 13:05:42 [2983] [CRITICAL] WORKER TIMEOUT (pid:3757)
2014-07-01 13:05:42 [2983] [CRITICAL] WORKER TIMEOUT (pid:3760)
2014-07-01 13:05:42 [2983] [CRITICAL] WORKER TIMEOUT (pid:3759)
2014-07-01 13:05:43,023 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 13:05:43,096 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 13:05:43,197 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 13:05:43,212 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 13:05:43,214 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 13:05:43,232 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 14:44:16 [2983] [CRITICAL] WORKER TIMEOUT (pid:8832)
2014-07-01 14:44:16 [2983] [CRITICAL] WORKER TIMEOUT (pid:8833)
2014-07-01 14:44:16 [2983] [CRITICAL] WORKER TIMEOUT (pid:8834)
2014-07-01 14:44:16 [2983] [CRITICAL] WORKER TIMEOUT (pid:3756)
2014-07-01 14:44:16 [2983] [CRITICAL] WORKER TIMEOUT (pid:3761)
2014-07-01 14:44:16 [2983] [CRITICAL] WORKER TIMEOUT (pid:3753)
2014-07-01 14:44:16 [2983] [CRITICAL] WORKER TIMEOUT (pid:8829)
2014-07-01 14:44:16 [2983] [CRITICAL] WORKER TIMEOUT (pid:8830)
2014-07-01 14:44:16 [2983] [CRITICAL] WORKER TIMEOUT (pid:8831)
2014-07-01 14:44:17,467 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 14:44:17,482 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 14:44:17,635 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 14:44:17,726 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 14:44:17,741 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 14:44:17,895 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 14:44:17,907 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 14:44:17,972 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 14:44:17,978 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 17:27:38 [2983] [CRITICAL] WORKER TIMEOUT (pid:10944)
2014-07-01 17:27:38 [2983] [CRITICAL] WORKER TIMEOUT (pid:10946)
2014-07-01 17:27:38 [2983] [CRITICAL] WORKER TIMEOUT (pid:10952)
2014-07-01 17:27:38 [2983] [CRITICAL] WORKER TIMEOUT (pid:10958)
2014-07-01 17:27:38 [2983] [CRITICAL] WORKER TIMEOUT (pid:10942)
2014-07-01 17:27:38,604 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 17:27:38,830 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 17:27:38,851 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 17:27:38,864 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 17:27:38,896 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:16:59 [2983] [CRITICAL] WORKER TIMEOUT (pid:10951)
2014-07-01 19:16:59 [2983] [CRITICAL] WORKER TIMEOUT (pid:10959)
2014-07-01 19:16:59 [2983] [CRITICAL] WORKER TIMEOUT (pid:11706)
2014-07-01 19:16:59 [2983] [CRITICAL] WORKER TIMEOUT (pid:11707)
2014-07-01 19:16:59 [2983] [CRITICAL] WORKER TIMEOUT (pid:11708)
2014-07-01 19:16:59 [2983] [CRITICAL] WORKER TIMEOUT (pid:11709)
2014-07-01 19:16:59 [2983] [CRITICAL] WORKER TIMEOUT (pid:11710)
2014-07-01 19:16:59,586 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:16:59,742 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:16:59,786 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:16:59,810 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:16:59,860 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:16:59,887 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:16:59,903 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:17:10,826 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:17:10,956 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:17:10,990 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:17:11,043 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:17:11,055 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:17:11,071 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:17:11,114 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:17:11,124 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 19:17:11,135 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-01 23:42:02,657 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-01 23:42:03,707 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-01 23:42:04,309 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-01 23:42:04,635 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-01 23:42:04,788 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-01 23:42:04,982 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-01 23:42:05,143 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-01 23:42:05,317 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-01 23:42:09,452 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-02 08:21:49 [2983] [CRITICAL] WORKER TIMEOUT (pid:12673)
2014-07-02 08:21:49 [2983] [CRITICAL] WORKER TIMEOUT (pid:12676)
2014-07-02 08:21:49 [2983] [CRITICAL] WORKER TIMEOUT (pid:12677)
2014-07-02 08:21:49 [2983] [CRITICAL] WORKER TIMEOUT (pid:12671)
2014-07-02 08:21:49,770 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 08:21:49,779 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 08:21:49,781 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 08:21:49,790 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 10:59:32 [2983] [CRITICAL] WORKER TIMEOUT (pid:12672)
2014-07-02 10:59:32 [2983] [CRITICAL] WORKER TIMEOUT (pid:30641)
2014-07-02 10:59:36,283 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 10:59:36,285 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 12:14:11 [2983] [CRITICAL] WORKER TIMEOUT (pid:5356)
2014-07-02 12:14:11 [2983] [CRITICAL] WORKER TIMEOUT (pid:5357)
2014-07-02 12:14:11 [2983] [CRITICAL] WORKER TIMEOUT (pid:30640)
2014-07-02 12:14:11 [2983] [CRITICAL] WORKER TIMEOUT (pid:30642)
2014-07-02 12:14:11 [2983] [CRITICAL] WORKER TIMEOUT (pid:30643)
2014-07-02 12:14:12,268 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 12:14:12,347 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 12:14:12,356 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 12:14:12,430 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 12:14:12,443 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 13:46:03 [2983] [CRITICAL] WORKER TIMEOUT (pid:12675)
2014-07-02 13:46:04 [2983] [CRITICAL] WORKER TIMEOUT (pid:12678)
2014-07-02 13:46:04 [2983] [CRITICAL] WORKER TIMEOUT (pid:12679)
2014-07-02 13:46:04 [2983] [CRITICAL] WORKER TIMEOUT (pid:6172)
2014-07-02 13:46:09,001 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 13:46:09,001 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 13:46:09,003 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 13:46:09,004 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 21:12:29,058 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 21:12:29,176 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 21:12:29,207 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 21:12:29,265 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 21:12:29,392 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 21:12:29,396 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 21:12:29,422 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 21:12:29,424 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-02 21:12:29,477 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 12:53:21 [4036] [CRITICAL] WORKER TIMEOUT (pid:4041)
2014-07-03 12:53:22,402 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:18:37 [4036] [CRITICAL] WORKER TIMEOUT (pid:4042)
2014-07-03 14:18:37 [4036] [CRITICAL] WORKER TIMEOUT (pid:4044)
2014-07-03 14:18:37 [4036] [CRITICAL] WORKER TIMEOUT (pid:4045)
2014-07-03 14:18:37 [4036] [CRITICAL] WORKER TIMEOUT (pid:4046)
2014-07-03 14:18:37 [4036] [CRITICAL] WORKER TIMEOUT (pid:4047)
2014-07-03 14:18:37 [4036] [CRITICAL] WORKER TIMEOUT (pid:4048)
2014-07-03 14:18:37 [4036] [CRITICAL] WORKER TIMEOUT (pid:4049)
2014-07-03 14:18:39,074 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:18:39,088 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:18:39,099 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:18:39,105 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:18:39,144 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:18:39,181 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:18:39,214 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:23:10,121 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:23:10,157 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:23:10,261 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:23:10,265 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:23:10,275 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:23:10,301 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:23:10,306 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:23:10,338 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 14:23:10,338 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:03:38,598 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:03:38,599 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:03:38,602 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:03:38,602 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:03:38,684 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:03:38,686 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:03:38,720 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:03:38,747 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:03:38,748 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:13:51,994 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:13:51,994 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:13:51,994 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:13:51,996 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:13:51,997 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:13:51,997 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:13:51,997 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:13:51,997 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:13:51,999 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:16:23,544 Exception on /checkCaptcha [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joseph/Dropbox/Current projects/GCLC/GCLC_Exp1/mtGCLC1/custom.py", line 51, in checkCaptcha
    print response.text
IOError: [Errno 5] Input/output error
2014-07-03 15:20:47,524 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:20:47,794 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:20:48,197 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:20:48,297 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:20:48,321 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:20:48,389 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:20:48,563 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:20:48,599 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:20:48,628 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:33:09,600 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:33:09,801 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:33:09,825 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:33:09,830 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:33:09,838 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:33:09,853 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:33:09,871 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:33:09,913 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:33:09,913 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:38:17,277 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:38:17,515 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:38:17,765 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:38:18,099 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:38:18,181 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:38:18,199 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:38:18,203 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:38:18,234 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 15:38:18,252 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:32 [15695] [CRITICAL] WORKER TIMEOUT (pid:15729)
2014-07-03 16:55:32 [15695] [CRITICAL] WORKER TIMEOUT (pid:15700)
2014-07-03 16:55:32 [15695] [CRITICAL] WORKER TIMEOUT (pid:15701)
2014-07-03 16:55:32 [15695] [CRITICAL] WORKER TIMEOUT (pid:15706)
2014-07-03 16:55:32 [15695] [CRITICAL] WORKER TIMEOUT (pid:15707)
2014-07-03 16:55:32 [15695] [CRITICAL] WORKER TIMEOUT (pid:15708)
2014-07-03 16:55:32 [15695] [CRITICAL] WORKER TIMEOUT (pid:15709)
2014-07-03 16:55:32 [15695] [CRITICAL] WORKER TIMEOUT (pid:15710)
2014-07-03 16:55:32,689 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:32,717 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:32,936 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:33,070 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:33,083 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:33,136 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:33,158 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:33,172 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:39,781 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:39,896 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:39,935 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:40,019 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:40,070 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:40,075 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:40,096 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:40,154 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-03 16:55:40,161 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-06 14:43:28,459 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-06 14:43:28,642 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-06 14:43:28,882 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-06 14:43:28,945 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-06 14:43:29,039 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-06 14:43:29,080 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-06 14:43:29,088 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-06 14:43:29,095 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-06 14:43:29,161 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 14:04:17,692 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 14:04:17,706 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 14:04:17,722 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 14:04:17,728 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 14:04:17,743 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 14:04:17,796 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 14:04:17,801 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 14:04:17,823 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 14:04:17,826 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 15:09:54,352 Exception on /stimuli [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: stimuli
2014-07-07 15:10:01,824 Exception on /stimuli/babble1.mp3 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: stimuli/babble1.mp3
2014-07-07 15:11:41,466 Exception on /css/index.css [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: css/index.css
2014-07-07 15:11:54,005 Exception on /css/style.css [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 558, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: css/style.css
2014-07-07 18:58:15 [26691] [CRITICAL] WORKER TIMEOUT (pid:26697)
2014-07-07 18:58:15 [26691] [CRITICAL] WORKER TIMEOUT (pid:26698)
2014-07-07 18:58:15 [26691] [CRITICAL] WORKER TIMEOUT (pid:26699)
2014-07-07 18:58:15 [26691] [CRITICAL] WORKER TIMEOUT (pid:26700)
2014-07-07 18:58:15 [26691] [CRITICAL] WORKER TIMEOUT (pid:26701)
2014-07-07 18:58:15 [26691] [CRITICAL] WORKER TIMEOUT (pid:26702)
2014-07-07 18:58:15 [26691] [CRITICAL] WORKER TIMEOUT (pid:26704)
2014-07-07 18:58:20,510 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:58:20,510 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:58:20,512 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:58:20,513 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:58:20,514 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:58:20,514 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:58:20,514 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:59:35,636 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:59:35,688 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:59:35,760 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:59:35,763 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:59:35,766 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:59:35,818 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:59:35,820 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:59:35,829 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 18:59:35,830 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 23:46:31,803 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 23:46:31,887 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 23:46:31,916 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 23:46:31,944 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 23:46:31,975 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 23:46:32,024 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 23:46:32,027 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 23:46:32,066 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-07 23:46:32,138 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:03 [3529] [CRITICAL] WORKER TIMEOUT (pid:3564)
2014-07-08 11:32:03 [3529] [CRITICAL] WORKER TIMEOUT (pid:3546)
2014-07-08 11:32:04,320 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:04,320 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:44,001 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:44,164 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:44,186 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:44,282 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:44,302 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:44,309 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:44,312 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:44,314 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 11:32:44,333 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 13:27:53,767 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 13:27:54,024 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 13:27:54,183 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 13:27:54,313 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 13:27:54,319 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 13:27:54,332 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 13:27:54,364 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 13:27:54,431 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 13:27:54,489 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 14:56:46 [3696] [CRITICAL] WORKER TIMEOUT (pid:3734)
2014-07-08 14:56:46 [3696] [CRITICAL] WORKER TIMEOUT (pid:3735)
2014-07-08 14:56:46 [3696] [CRITICAL] WORKER TIMEOUT (pid:3706)
2014-07-08 14:56:47,073 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 14:56:47,079 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 14:56:47,084 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 23:10:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:3728)
2014-07-08 23:10:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:3702)
2014-07-08 23:10:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:3708)
2014-07-08 23:10:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:8537)
2014-07-08 23:10:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:8533)
2014-07-08 23:10:47,876 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 23:10:47,876 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 23:10:47,877 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 23:10:47,878 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-08 23:10:47,881 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-09 09:06:07 [3696] [CRITICAL] WORKER TIMEOUT (pid:19959)
2014-07-09 09:06:07 [3696] [CRITICAL] WORKER TIMEOUT (pid:19964)
2014-07-09 09:06:08,130 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-09 09:06:08,132 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-09 12:01:10,114 Exception on /lagcomp.html [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: lagcomp.html
2014-07-09 12:01:37,691 Exception on /lagcomp.html [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: lagcomp.html
2014-07-09 15:33:04,508 Exception on /list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/experiment.py", line 556, in regularpage
    return render_template(pagename)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: list
2014-07-09 22:34:09 [3696] [CRITICAL] WORKER TIMEOUT (pid:19961)
2014-07-09 22:34:16,178 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 08:25:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:23944)
2014-07-10 08:25:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:20654)
2014-07-10 08:25:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:20655)
2014-07-10 08:25:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:3701)
2014-07-10 08:25:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:19958)
2014-07-10 08:25:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:3703)
2014-07-10 08:25:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:8536)
2014-07-10 08:25:43 [3696] [CRITICAL] WORKER TIMEOUT (pid:3705)
2014-07-10 08:25:48,973 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 08:25:48,974 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 08:25:48,974 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 08:25:48,975 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 08:25:48,976 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 08:25:48,979 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 08:25:48,979 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 08:25:48,986 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:48:34 [3696] [CRITICAL] WORKER TIMEOUT (pid:31916)
2014-07-10 10:48:34 [3696] [CRITICAL] WORKER TIMEOUT (pid:31917)
2014-07-10 10:48:34 [3696] [CRITICAL] WORKER TIMEOUT (pid:31921)
2014-07-10 10:48:34 [3696] [CRITICAL] WORKER TIMEOUT (pid:31922)
2014-07-10 10:48:34 [3696] [CRITICAL] WORKER TIMEOUT (pid:31925)
2014-07-10 10:48:39,379 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:48:39,379 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:48:39,380 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:48:39,382 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:48:39,384 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:52:44,184 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:52:44,195 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:52:44,226 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:52:44,230 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:52:44,234 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:52:44,246 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:52:44,250 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:52:44,257 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:52:44,271 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:56:03,812 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:56:03,816 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:56:03,819 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:56:03,819 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:56:03,819 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:56:03,821 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:56:03,821 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:56:03,822 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 10:56:03,824 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 13:23:28 [3734] [CRITICAL] WORKER TIMEOUT (pid:3751)
2014-07-10 13:23:28 [3734] [CRITICAL] WORKER TIMEOUT (pid:3755)
2014-07-10 13:23:28 [3734] [CRITICAL] WORKER TIMEOUT (pid:3740)
2014-07-10 13:23:30,979 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 13:23:30,979 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 13:23:30,979 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 14:59:27 [3734] [CRITICAL] WORKER TIMEOUT (pid:3746)
2014-07-10 14:59:27 [3734] [CRITICAL] WORKER TIMEOUT (pid:9003)
2014-07-10 14:59:27 [3734] [CRITICAL] WORKER TIMEOUT (pid:3754)
2014-07-10 14:59:27 [3734] [CRITICAL] WORKER TIMEOUT (pid:9002)
2014-07-10 14:59:27 [3734] [CRITICAL] WORKER TIMEOUT (pid:9004)
2014-07-10 14:59:27 [3734] [CRITICAL] WORKER TIMEOUT (pid:3739)
2014-07-10 14:59:27 [3734] [CRITICAL] WORKER TIMEOUT (pid:3742)
2014-07-10 14:59:28,135 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 14:59:28,169 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 14:59:28,230 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 14:59:28,321 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 14:59:28,417 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 14:59:28,447 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 14:59:28,450 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:24:44 [3734] [CRITICAL] WORKER TIMEOUT (pid:10417)
2014-07-10 19:24:44 [3734] [CRITICAL] WORKER TIMEOUT (pid:10418)
2014-07-10 19:24:44 [3734] [CRITICAL] WORKER TIMEOUT (pid:10419)
2014-07-10 19:24:44 [3734] [CRITICAL] WORKER TIMEOUT (pid:3741)
2014-07-10 19:24:51,033 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:24:51,034 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:24:51,036 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:24:51,039 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:25:18,953 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:25:19,036 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:25:19,103 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:25:19,115 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:25:19,125 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:25:19,150 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:25:19,150 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:25:19,161 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-10 19:25:19,173 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 11:22:29,755 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 11:22:29,872 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 11:22:30,033 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 11:22:30,059 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 11:22:30,179 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 11:22:30,236 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 11:22:30,319 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 11:22:30,381 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 11:22:30,399 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 15:01:30 [3489] [CRITICAL] WORKER TIMEOUT (pid:3494)
2014-07-11 15:01:30 [3489] [CRITICAL] WORKER TIMEOUT (pid:3495)
2014-07-11 15:01:30 [3489] [CRITICAL] WORKER TIMEOUT (pid:3497)
2014-07-11 15:01:35,346 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 15:01:35,347 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 15:01:35,347 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-11 19:31:16 [3489] [CRITICAL] WORKER TIMEOUT (pid:3496)
2014-07-11 19:31:23,968 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 09:40:48 [3489] [CRITICAL] WORKER TIMEOUT (pid:7881)
2014-07-12 09:40:49 [3489] [CRITICAL] WORKER TIMEOUT (pid:12681)
2014-07-12 10:38:43 [3489] [CRITICAL] WORKER TIMEOUT (pid:18539)
2014-07-12 10:38:43 [3489] [CRITICAL] WORKER TIMEOUT (pid:7882)
2014-07-12 10:38:43 [3489] [CRITICAL] WORKER TIMEOUT (pid:3527)
2014-07-12 10:38:43 [3489] [CRITICAL] WORKER TIMEOUT (pid:3500)
2014-07-12 10:38:43 [3489] [CRITICAL] WORKER TIMEOUT (pid:3535)
2014-07-12 10:38:43 [3489] [CRITICAL] WORKER TIMEOUT (pid:7880)
2014-07-12 10:38:43 [3489] [CRITICAL] WORKER TIMEOUT (pid:3513)
2014-07-12 10:38:43 [3489] [CRITICAL] WORKER TIMEOUT (pid:3514)
2014-07-12 10:38:47,714 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 10:38:47,717 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 10:38:47,717 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 10:38:47,718 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 10:38:47,718 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 10:38:47,721 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 10:38:47,725 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 10:38:47,727 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 10:38:47,764 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 20:31:17 [3489] [CRITICAL] WORKER TIMEOUT (pid:18816)
2014-07-12 20:31:32,395 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 23:14:36 [3489] [CRITICAL] WORKER TIMEOUT (pid:18817)
2014-07-12 23:14:36 [3489] [CRITICAL] WORKER TIMEOUT (pid:18810)
2014-07-12 23:14:36 [3489] [CRITICAL] WORKER TIMEOUT (pid:18812)
2014-07-12 23:14:50,303 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 23:14:50,304 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-12 23:14:57,719 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 11:29:18 [3489] [CRITICAL] WORKER TIMEOUT (pid:18818)
2014-07-13 11:29:18 [3489] [CRITICAL] WORKER TIMEOUT (pid:18811)
2014-07-13 11:29:18 [3489] [CRITICAL] WORKER TIMEOUT (pid:26238)
2014-07-13 11:29:27,475 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 11:29:27,475 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 11:29:29,645 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:28:57 [3489] [CRITICAL] WORKER TIMEOUT (pid:28009)
2014-07-13 16:28:57 [3489] [CRITICAL] WORKER TIMEOUT (pid:3500)
2014-07-13 16:28:57 [3489] [CRITICAL] WORKER TIMEOUT (pid:18814)
2014-07-13 16:28:57 [3489] [CRITICAL] WORKER TIMEOUT (pid:3497)
2014-07-13 16:28:57 [3489] [CRITICAL] WORKER TIMEOUT (pid:27962)
2014-07-13 16:28:57 [3489] [CRITICAL] WORKER TIMEOUT (pid:18815)
2014-07-13 16:29:01,208 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:29:01,210 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:29:01,210 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:29:01,210 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:29:01,211 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:29:01,212 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:39:29 [3489] [CRITICAL] WORKER TIMEOUT (pid:11078)
2014-07-13 16:39:29 [3489] [CRITICAL] WORKER TIMEOUT (pid:11043)
2014-07-13 16:39:29 [3489] [CRITICAL] WORKER TIMEOUT (pid:11044)
2014-07-13 16:39:29 [3489] [CRITICAL] WORKER TIMEOUT (pid:11045)
2014-07-13 16:39:29 [3489] [CRITICAL] WORKER TIMEOUT (pid:11047)
2014-07-13 16:39:29 [3489] [CRITICAL] WORKER TIMEOUT (pid:11048)
2014-07-13 16:39:29 [3489] [CRITICAL] WORKER TIMEOUT (pid:27960)
2014-07-13 16:39:29 [3489] [CRITICAL] WORKER TIMEOUT (pid:3513)
2014-07-13 16:39:29 [3489] [CRITICAL] WORKER TIMEOUT (pid:18813)
2014-07-13 16:39:30,132 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:39:30,174 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:39:30,265 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:39:30,335 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:39:30,362 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:39:30,401 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:39:30,408 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:39:30,454 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 16:39:30,472 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2014-07-13 22:20:50,267 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 22:20:50,267 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 22:20:50,316 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 22:20:50,436 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 22:20:50,550 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 22:20:50,582 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 22:20:50,593 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 22:20:50,602 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-13 22:20:50,640 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:45:37 [6385] [CRITICAL] WORKER TIMEOUT (pid:6390)
2014-07-14 09:45:37 [6385] [CRITICAL] WORKER TIMEOUT (pid:6392)
2014-07-14 09:45:37 [6385] [CRITICAL] WORKER TIMEOUT (pid:6397)
2014-07-14 09:45:39,990 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:45:39,990 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:45:39,992 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:46:20,245 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:46:20,310 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:46:20,365 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:46:20,374 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:46:20,380 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:46:20,411 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:46:20,416 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:46:20,422 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 09:46:20,438 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 10:30:31,229 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 10:30:31,266 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 10:30:31,299 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 10:30:31,304 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 10:30:31,354 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 10:30:31,418 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 10:30:31,470 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 10:30:31,497 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
2014-07-14 10:30:31,506 /usr/local/lib/python2.7/dist-packages/psiturk/psiturk_js/psiturk.js
